n =input('Digite algo: ')
print(f'O tipo primitivo é? ', n.__class__)
print(f'Só tem espaços? ', n.isspace())
print(f'É um número? ', n.isnumeric())
print(f'É alfabético? ', n.isalpha())
print(f'É alfanumérico? ', n.isalnum())
print(f'Está em maiúscula? ', n.isupper())
print(f'Está em minúscula? ', n.islower())
print(f'Está capitalizada? ', n.istitle())